services:
  bentopdf-test2:
    image: bentopdf-test2:latest
    container_name: bentopdf-test2
    ports:
      - '8089:8080'
    restart: unless-stopped
    # For IPv4-only environments
    environment:
     - DISABLE_IPV6=true
    #  - ROBOTS_NOINDEX=true
    volumes:
      - ./config.json:/usr/share/nginx/html/config.json:ro